version: 0.2
    
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - chmod +x ./script/git.helper.sh
      - npm ci
  build:
    commands:
      - ./script/git.helper.sh develop
      - npm run-script build
artifacts:
    files:
      - '**/*'
    base-directory: 'dist'
