name: QS

on:
  pull_request:
    branches:
    - master

jobs:
  qs:
    name: 'QS'
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install (node_modules))"
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          cache-key: node-on-${{ runner.os }}-hash-${{ hashFiles('**/package-lock.json') }}

      - name: "License check"
        id: copyleft
        run: npm run licenses

      - name: "Lint checking (ESLint)"
        id: eslint
        run: npm run lint:report
        continue-on-error: true

      - name: "Code linting (ESLint)"
        uses: ataylorme/eslint-annotate-action@f92355332c64bc5c2d474cc6555edcb1315fdd12
        if: github.actor != 'dependabot[bot]'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: lint.json

      - name: Upload ESLint report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint.json
          path: lint.json

  build:
    name: 'Build'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'master'
    container: cypress/browsers:node14.15.0-chrome86-ff82
    needs: qs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install all (node_modules) and build (dev)"
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          build: npm run build
          cache-key: node-on-${{ runner.os }}-hash-${{ hashFiles('**/package-lock.json') }}

      - name: Cache build folder
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ github.sha }}
